services:
  mongodb:
    image: mongo:8.0.4
    container_name: mongodb_container
    ports:
      - "27018:27017"
    networks:
      - ecommerce_network
    volumes:
      - mongo_data:/data/db

  ecommerce-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecommerce_api_container
    ports:
      - "8081:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      TZ: "America/Bogota"
    depends_on:
      - mongodb
    networks:
      - ecommerce_network

networks:
  ecommerce_network:
    driver: bridge

volumes:
  mongo_data:
    driver: local
