server:
  host: localhost
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/ecommerce_db

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
